---
- name: Create incident with notes
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Create an incident
    servicenow.itsm.incident:
      instance:
        host: "{{ sn_instance }}"
        username: "{{ sn_username }}"
        password: "{{ sn_password }}"

      state: new
      caller: some.user
      short_description: User is not receiving email
      description: User has been unable to receive email for the past 15 minutes
      impact: low
      urgency: low
